### ISSUE TITLE
OpenUPM support

### ISSUE THREAD

**Issue by rhys-vdw** [TextusGames/UnitySerializedReferenceUI#12]
Hi there, your project has been listen on OpenUPM, but due to not having any semver-compatible tags is not available for download.

Would you be open to tagging the most recent release with its correct semver version so that it can be downloaded from the OpenUPM server?

https://openupm.com/packages/com.textus-games.serialized-reference-ui/

**Comment by TextusGames** [comment]
I created the release with v1.1.0 tag. Hope that helps.

**Comment by TextusGames** [comment]
Hello.
Thank you for pointing that out.
I have created a release.
And it seems like a package has been builded on the OpenUpm site.
There is however a difference in version and tag version.
I hope this does not cause any problems.
If there are any problems with the package, feel free to let me know.
[image: image.png]

**Comment by rhys-vdw** [comment]
Yeah, it seems like you've tagged version 1.0.0 as 1.1.0? In any case only the 1.0.0 tag is available on OpenUPM so thanks. :-)
