### ISSUE TITLE
2021.1.1f1 inspector issue

### ISSUE THREAD

**Issue by ChiefBreakeverything** [TextusGames/UnitySerializedReferenceUI#7]
Hey there,

I just noticed that the inspector layout seems to have broken in Unity 2021.1.1f1 (it worked great in 2020.x.x for me).

If you have an array using [SerializeReferenceButton], unfolding any element in the array will prevent the following elements from being drawn like so:

![image](https://user-images.githubusercontent.com/4685982/117285284-34002f00-aeab-11eb-8683-68398b2bf27b.png)

Any idea whats happening here?

**Comment by TextusGames** [comment]
![image](https://user-images.githubusercontent.com/34438607/117484519-d41f8c00-af6f-11eb-840e-ffd18e6c981a.png)
EditorGUI.BeginProperty(..) makes this happen.
If you comment out this call. It should be drawn normally.

It is kind of regression from unity side.
I filed a bug report - https://fogbugz.unity3d.com/default.asp?1334600_s5sjnu3n67f0qm6j

**Comment by TextusGames** [comment]
I have got email that issue 1334600 is fixed in Unity 2021.2.0a20

**Comment by virgile-wp** [comment]
I still got a similar issue with 2021.2.4f1:
When I click in hierarchy on a gameobject with a `SerializeReferenceButtonAttribute`,
in the property grid, I can see all elements for a single frame, then elements after the first one disappear.
If I collapse the first element, the following elements come back (and it's still there when I expand it again).

Commenting those two lines fixes it for now.
